import { dir } from 'i18next';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import type { PropsWithChildren, ReactElement } from 'react';

import '../globals.css';

import type { Languages } from 'src/lib/i18n/types';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
    params: { lng },
}: PropsWithChildren<{ params: { lng: Languages } }>): ReactElement {
    return (
        <html lang={lng} dir={dir(lng)}>
            <body className={inter.className}>{children}</body>
        </html>
    );
}
